### ISSUE TITLE
MVP Punch List for Friends of Pods

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-friends#18]
Putting out the remainder of Tasks that need to be completed to retire https://pods.io/friends-of-pods/ and validate that we're working at https://friends.pods.io

- [ ] Finish content for Front Page #6 
- [ ] Pricing / Reward Levels Conversion, new pricing structure #9 
- [ ] JOIN Page (with links for all forms)
- [ ] Why be a partner page
- [x] Lockdown My Account and sub-pages specific to account that require you to be logged-in
- [ ] Page Footer (Validate Global Footer works)
- [x] Pods Team Widget / About Our Team Page #19 
- [x] Special Thanks Widget / Special Thanks Page #20
- [x] Add social links and menu back to Pods.io to the top
